# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch Workflow

on:
  push:
    branches: [main]

jobs:
  build_python_artifacts:
    name: Python Build
    uses: jondavid-black/AaC/.github/workflows/python-build-artifacts.yml@5f36be5cb244cad6aaa226fb6cbae07a63ad9074

  build_vscode_artifacts:
    name: VSCode Extension Build
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/vscode-build-artifacts.yml@5f36be5cb244cad6aaa226fb6cbae07a63ad9074

  python_tests:
    name: Python Tests
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/python-tests.yml@5f36be5cb244cad6aaa226fb6cbae07a63ad9074
