# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch Workflow

on:
  push:
    branches: [main]

jobs:
  build_python_artifacts:
    name: Build Python Artifacts
    uses: jondavid-black/AaC/.github/workflows/python-build-artifacts.yml@1ea67a9e3ecb7939d19e0fb981b1ee32d829d479

  build_vscode_artifacts:
    name: Build VSCode Extension Artifacts
    uses: jondavid-black/AaC/.github/workflows/vscode-build-artifacts.yml@1ea67a9e3ecb7939d19e0fb981b1ee32d829d479

  python_functional_tests:
    name: Python Functional Tests
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/python-functional-tests.yml@1ea67a9e3ecb7939d19e0fb981b1ee32d829d479
