# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch Workflow

on:
  push:
    branches: [main]

jobs:
  build_python_artifacts:
    name: Python Build
    uses: ./.github/workflows/python-build-and-lint.yml

  build_vscode_artifacts:
    name: VSCode Extension Build
    needs: build_python_artifacts
    uses: ./.github/workflows/vscode-build-artifacts.yml

  python_tests:
    name: Python Unit Tests
    needs: build_python_artifacts
    uses: ./.github/workflows/python-test-python-version.yml

  python_cross_platform:
    name: Python Cross Platform Build & Test
    uses: ./.github/workflows/python-cross-platform-support.yml
 
  build_and_deploy_documentation:
    name: Build and Deploy GitHub Pages
    uses: ./.github/workflows/sphinx.yml
