# This workflow is only intended to run when a pull-request is merged into the main branch
name: Main branch AaC Workflow

on:
  push:
    branches: [main]

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@0fea358c040d9cdc3055e523f34718f6d5c6eed1

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@0fea358c040d9cdc3055e523f34718f6d5c6eed1

  Deploy_Artifacts:
    needs: Run_Functional_Tests
    uses: jondavid-black/AaC/.github/workflows/deploy-artifacts.yml@0fea358c040d9cdc3055e523f34718f6d5c6eed1
