# This workflow is intended to run for ANY pull request
name: Pull Requests AaC Workflow

on:
  pull_request:

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@0fea358c040d9cdc3055e523f34718f6d5c6eed1

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@eb8a6a625e759ffc837569ac270577096e8a31cf