# This workflow is intended to run for ANY pull request
name: Pull Requests AaC Workflow

on:
  pull_request:

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@1e3f89c23eb6583116848d81ccd5ad952f9a62b6

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@478dcf62c5a8180ab6be4fc6204e0d117d69aedf
    # uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@80bdd88b0d35b04c14d7e54d4c1de1c3f2ef0e69
