# This workflow is intended to run for ANY pull request
name: Pull Request Workflow

on:
  pull_request:

jobs:
  build_python_artifacts:
    name: Build Python Artifacts
    uses: jondavid-black/AaC/.github/workflows/python-build-artifacts.yml@923464a8542c6cfa46018b45f50f1ffc455d5de9

  build_vscode_artifacts:
    name: Build VSCode Extension Artifacts
    uses: jondavid-black/AaC/.github/workflows/vscode-build-artifacts.yml@923464a8542c6cfa46018b45f50f1ffc455d5de9

  python_functional_tests:
    name: Python Functional Tests
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/python-functional-tests.yml@923464a8542c6cfa46018b45f50f1ffc455d5de9
