# This workflow is intended to run for ANY pull request
name: Pull Request Workflow

on:
  pull_request:

jobs:
  build_python_artifacts:
    name: Python Build
    uses: jondavid-black/AaC/.github/workflows/python-build-artifacts.yml

  build_vscode_artifacts:
    name: VSCode Ext. Build
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/vscode-build-artifacts.yml

  python_tests:
    name: Python Tests
    needs: build_python_artifacts
    uses: jondavid-black/AaC/.github/workflows/python-tests.yml
