# This workflow is intended to run for ANY pull request
name: Pull Requests AaC Workflow

on:
  pull_request:

jobs:
  Build_Package_and_Artifacts:
    uses: jondavid-black/AaC/.github/workflows/build-artifacts.yml@a3ffb8e025a1c30d4f2a09c97cd964ec28474650

  Run_Functional_Tests:
    needs: Build_Package_and_Artifacts
    uses: jondavid-black/AaC/.github/workflows/functional-tests.yml@a3ffb8e025a1c30d4f2a09c97cd964ec28474650
