# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libgirepository1.0-dev -y
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Pip
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pip
      - name: Install the AaC Package
        run: pip install -e .[all]
      - name: List Transitive Dependencies
        run: |
          pipdeptree
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --select=E9,F63,F7,F82
          # exit-zero treats all errors as warnings.
          flake8 . --exit-zero
      - name: Test with Tox
        run: |
          tox -- --coverage-report html
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: html_code_coverage/
      - name: Validate Core Spec and Plugin Specs
        run: |
          find src -name spec.yaml -print0 | xargs -0 -n1 aac validate
          find plugins -name *.yaml -print0 | xargs -0 -n1 aac validate
      - name: Generate API Documentation
        run: |
          cd docs/
          make html
      - name: Upload API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: api-documentation
          path: docs/build/html/
      - name: Build distribution package
        run: |
          python setup.py bdist_wheel
      # - name: Publish distribution to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
