on:
  workflow_call:

defaults:
  run:
    working-directory: ./python

jobs:
  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upload AaC models
        uses: actions/upload-artifact@v2
        with:
          name: aac-models
          path: python/model/

      - name: Install the AaC Package
        run: pip install -e .[all]

      - name: Lint with flake8
        run: flake8 .

      - name: List Transitive Dependencies
        run: pipdeptree

      - name: Create Dependencies Package
        run: |
          cd secure_install
          pip wheel ../
          pip-compile --generate-hashes ../setup.py
          mv ../requirements.txt .
          pip hash aac-*.whl >> requirements.txt
          tar -cvf secure_install.tar.gz .

      - name: Upload Dependencies Package
        uses: actions/upload-artifact@v2
        with:
          name: secure_install
          path: python/secure_install/secure_install.tar.gz

      - name: Generate API Documentation
        run: |
          cp -R ../docs/ ./docs
          cd ./docs/
          make html

      - name: Upload API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: api-documentation
          path: python/docs/build/html/

      - name: Generate RESTful API Documentation
        run: |
          mkdir oasv3-spec
          aac generate-openapi-spec oasv3-spec

      - name: Upload RESTful API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: rest-api-documentation
          path: python/oasv3-spec

      - name: Build distribution package
        run: python setup.py bdist_wheel

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v2
        with:
          name: aac_wheel
          path: python/dist/
