# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        run : |
          apt-get update
          apt-get install python3.9 python3.9-venv python3.9-tk -y
      - name: Install dependencies
        run: |
          python -m venv venv --system-site-packages
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .[all]
      - name: Lint with flake8
        run: |
          source venv/bin/activate
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --select=E9,F63,F7,F82
          # exit-zero treats all errors as warnings.
          flake8 . --exit-zero
      - name: Test with Tox
        run: |
          source venv/bin/activate
          tox -- --coverage-report html
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: html_code_coverage/
      - name: Validate Core Spec and Plugin Specs
        run: |
          source venv/bin/activate
          find . -name AaC.yaml -exec aac validate {} \;
          find plugins -name *.yaml -exec aac validate {} \;
      - name: Generate API Documentation
        run: |
          source venv/bin/activate
          cd docs/
          make html
      - name: Upload API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: api-documentation
          path: docs/build/html/
      - name: Build distribution package
        run: |
          source venv/bin/activate
          python setup.py bdist_wheel
      # - name: Publish distribution to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
