name: Build Python Artifacts

on:
  workflow_call:

defaults:
  run:
    working-directory: ./python

jobs:
  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    outputs:
      aac_package_version: ${{ steps.package_version.outputs.package_version }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install the AaC Package
        run: pip install -e .[all]

      - name: List Transitive Dependencies
        run: pipdeptree

      - name: Lint with flake8
        run: flake8 .

      - name: Test with Tox
        run: tox -- --coverage-report html

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: python/html_code_coverage/

      - name: Generate API Documentation
        run: |
          cp -R ../docs/ ./docs
          cd ./docs/
          make html

      - name: Upload API Documentation
        uses: actions/upload-artifact@v2
        with:
          name: api-documentation
          path: python/docs/build/html/

      - name: Build distribution package
        run: python setup.py bdist_wheel

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v2
        with:
          name: aac_wheel
          path: python/dist/
          
      - name: Get Package Version
        id: package_version
        run: echo "::set-output name=package_version::$(aac version | awk 'END{print}')"
